### ISSUE TITLE
Présumée "backdoor" présente dans le code

### ISSUE THREAD

**Issue by ghost** [TRIADE-EDUC/TRIADE#1]
Bonjour.
Windows Defender signale une présumée backdoor dans le fichier `demdst2.php` (`Backdoor:PHP/Chopper.E!dha`).

**Comment by Mr-Electro84** [comment]
Bonjour,

Il s'agit très certainement d'un faux positif liée à Windows Defender. Le fichier en question est sain (vous pouvez le vérifier [ici](https://www.virustotal.com/gui/url/5b4c425d570d1ec290233c1cbb590e5d9711d6263bda89d7007dffdef4eeb220) ).

Le problème n'est pas de notre ressort, le mieux reste de signaler le faux positif à Microsoft.
